export interface Inscription {
    registrationId: number,
    applicantType: string,
    modality: string,
    campus: string,
    program: string,
    academicPeriod: string,
    firstName: string,
    lastName: string,
    birthDate: string,
    birthCountry: string,
    birthDepartment: string,
    birthCity: string,
    bloodType: string,
    documentType: string,
    documentNumber: string,
    expeditionDate: string,
    expeditionCountry: string,
    expeditionDepartment: string,
    expeditionCity: string,
    sex: string,
    civilStatus: string,
    telephoneNumber: string,
    cellphoneNumber: string,
    email: string,
    direcction: string
}
